import React, { Component } from "react"

import { timelineStore, TODAY_MARKER_REFERENCE, ALL_WEEKS_CHANGED } from "../../../store"

import WeekComp from "../WeekComp/WeekComp"
import ClassBarRowComp from "../ClassBarRowComp/ClassBarRowComp"
import ClassTaskRowComp from "../ClassTaskRowComp/ClassTaskRowComp"
import loader from "../../../assets/images/Eclipse.gif"
import Buttons from "../Buttons/Buttons"
import classes from "./timeline.css"
import { appStore } from "../../../Provider";


export default class Timeline extends Component {
    state = {
        todayMarkerRef: null,
        scrollingParentRef: null,
        local_update: false,
        allWeeks: null
    }

    setTodayMarkerRef = ref => {
        this.setState({ todayMarkerRef: ref })
    }

    renderWeekComp = () => {
        if (!this.state.allWeeks) return null
        const { rowHeight, itemWidth } = this.props
        return (
            <div className={classes.rowContainer}>
                {this.state.allWeeks.map(week => (
                    <WeekComp
                        setTodayMarkerRef={this.setTodayMarkerRef}
                        scrollingParentRef={this.refs.timelineWrapper}
                        key={week}
                        week={week}
                        rowHeight={rowHeight}
                        itemWidth={itemWidth}
                    />
                ))}
            </div>
        )
    }

    renderTaskRowComp = () => {
        if (
            !this.props.groups ||
            !this.props.timelineItems ||
            !this.state.allWeeks
        )
        // implement the loader giv
        {
            return (
                <div className={classes.divLoading}>
                    <img src={loader} alt="loader" className={classes.load} />
                </div>
            )
        }
        // console.log(appStore.state)
        const { groups, items: timelineItems } = appStore.state.timeline
        return groups.map(group => {
            const items = timelineItems[group]
            const { itemWidth, rowHeight } = this.props
            return (
                <div key={items[0].group_name} className={classes.rowContainer}>
                    <ClassTaskRowComp
                        isTeacher={this.props.isTeacher}
                        teachers={this.props.teachers}
                        selectedModule={this.props.selectedModule}
                        items={items}
                        width={itemWidth}
                        height={rowHeight}
                        allWeeks={this.state.allWeeks}
                        itemClickHandler={this.props.itemClickHandler}
                        infoSelectedModule={this.props.infoSelectedModule}
                    />

                </div>
            )
        })
    }

    observer = mergedData => {
        switch (mergedData.type) {
            case TODAY_MARKER_REFERENCE:
                this.setState({ todayMarkerRef: mergedData.payload.todayMarkerRef })
                break
            case ALL_WEEKS_CHANGED:
                this.setState({ allWeeks: mergedData.payload.allWeeks })
                break
            default:
                break
        }
    }

    handleClickTodayMarker = e => {
        const todayMarker = this.state.todayMarkerRef
        const classesContainer = this.refs.classesContainer.refs.groupsRowContainer // hackish way, hope good
        const scrollEl = this.refs.timelineWrapper
        let leftPos = todayMarker.parentNode.getBoundingClientRect().x
        leftPos -= scrollEl.offsetWidth / 2 - classesContainer.offsetWidth
        scrollEl.scrollLeft += leftPos
    }

    componentWillMount = () => {
        // so that it gets all setState notification from generated by componentDidMount of children elements
        timelineStore.subscribe(this.observer)
    }

    componentDidMount = () => {
        timelineStore.fetchItems(true)
        this.setState({
            local_update: true
        })
    }

    render() {
        const { itemWidth, rowHeight } = this.props
        const { allWeeks } = this.state
        // console.log(appStore.state)
        // if there items are fetched  width is the 200 times total weeks otherwise it's 100vh
        // FIXME: no idea why this is not working with just 16 instead of 21
        const width = allWeeks
            ? itemWidth * allWeeks.length + 21 * allWeeks.length + "px"
            : "100vw"
        return (

            <div className="rootContainer">
                <ClassBarRowComp
                    groups={appStore.state.timeline.groups}
                    rowHeight={rowHeight}
                    ref="classesContainer"
                />
                <div
                    className={classes.root}
                    ref="timelineWrapper"
                    onScroll={this.handleScroll}
                >
                    <div className={classes.timelineContainer} style={{ width: width }}>
                        <div className={classes.rowsContainer}>
                            {this.state.local_update && this.renderWeekComp()}
                            {this.state.local_update && this.renderTaskRowComp()}
                        </div>
                    </div>
                </div>
                <div ref="buttonsContainer" className={classes.buttonsContainer}>
                    <Buttons
                        clickHandler={this.handleClickTodayMarker}
                        isTeacher={appStore.state.main.auth.isATeacher}
                    />
                </div>
            </div>
        )
    }
}
